config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

root to: 'static#index'

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout',
to: 'sessions#destroy'

  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :pracowniks
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzials
  resources :pracowniks
  resources :hehies
  resources :hehs
  resources :hehehs
  resources :hehs
  resources :hehehs
  resources :hehehs
  resources :hehes
  resources :specjalizacjas
  resources :prac2specjalizacjas
  resources :oddzialies
  resources :prac2oddzials
  resources :pracowniks
  resources :rodzaj_pracownikas
  resources :wozyta
  resources :archiwums
  resources :pacjents
  resources :terminarzs
  resources :students
  resources :pracowniks
  resources :pracownikis
  resources :pracowniks

end

app/models/archiwum.rb
class Archiwum < ActiveRecord::Base
end

app/models/oddzialy.rb
class Oddzialy < ActiveRecord::Base
has_many :prac2oddzials
end

app/models/pacjent.rb
class Pacjent < ActiveRecord::Base
has_many :wizytums
end

app/models/prac2oddzial.rb
class Prac2oddzial < ActiveRecord::Base
end

app/models/prac2specjalizacja.rb
class Prac2specjalizacja < ActiveRecord::Base
end

app/models/pracownik.rb
class Pracownik < ActiveRecord::Base
has_many :prac2oddzials
has_many :prac2specjalizacjas
has_many :wizytums
has_many :terminarzs

has_secure_password
validates :imie, presence: true
validates :nazwisko, presence: true
validates :pesel, presence: true, uniqueness: true, length: { in: 3..50 }


end

app/models/rodzaj_pracownika.rb
class RodzajPracownika < ActiveRecord::Base
has_many :Pracowniks
end

app/models/specjalizacja.rb
class Specjalizacja < ActiveRecord::Base
has_many :prac2specjalizacjas
end

app/models/terminarz.rb
class Terminarz < ActiveRecord::Base
end

app/models/wizytum.rb
class Wizytum < ActiveRecord::Base
has_many :archiwums
end

app/controllers/pracowniks_controller.rb
class PracowniksController < ApplicationController
  before_action :set_pracownik, only: [:show, :edit, :update, :destroy]

  # GET /pracowniks
  # GET /pracowniks.json
  def index
    @pracowniks = Pracownik.all
  end

  # GET /pracowniks/1
  # GET /pracowniks/1.json
  def show
  end

  # GET /pracowniks/new
  def new
    @pracownik = Pracownik.new
  end

  # GET /pracowniks/1/edit
  def edit
  end

  # POST /pracowniks
  # POST /pracowniks.json
  def create
    @pracownik = Pracownik.new(pracownik_params)

    respond_to do |format|
      if @pracownik.save
        format.html { redirect_to @pracownik, notice: 'Pracownik was successfully created.' }
        format.json { render :show, status: :created, location: @pracownik }
      else
        format.html { render :new }
        format.json { render json: @pracownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pracowniks/1
  # PATCH/PUT /pracowniks/1.json
  def update
    respond_to do |format|
      if @pracownik.update(pracownik_params)
        format.html { redirect_to @pracownik, notice: 'Pracownik was successfully updated.' }
        format.json { render :show, status: :ok, location: @pracownik }
      else
        format.html { render :edit }
        format.json { render json: @pracownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pracowniks/1
  # DELETE /pracowniks/1.json
  def destroy
    @pracownik.destroy
    respond_to do |format|
      format.html { redirect_to pracowniks_url, notice: 'Pracownik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pracownik
      @pracownik = Pracownik.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pracownik_params
      params.require(:pracownik).permit(:ID_pracownika, :ID_rodzajprac, :imie, :nazwisko, :pesel, :data_zatrudnienia, :zarobki, :aktywny, :password, :password_confirmation)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

def index
@some_variable = 123
@pracowniks=Pracownik.all

end
end

app/controllers/wizyta_controller.rb
class WizytaController < ApplicationController
  before_action :set_wizytum, only: [:show, :edit, :update, :destroy]

  # GET /wizyta
  # GET /wizyta.json
  def index
    @wizyta = Wizytum.all
  end

  # GET /wizyta/1
  # GET /wizyta/1.json
  def show
  end

  # GET /wizyta/new
  def new
    @wizytum = Wizytum.new
  end

  # GET /wizyta/1/edit
  def edit
  end

  # POST /wizyta
  # POST /wizyta.json
  def create
    @wizytum = Wizytum.new(wizytum_params)

    respond_to do |format|
      if @wizytum.save
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully created.' }
        format.json { render :show, status: :created, location: @wizytum }
      else
        format.html { render :new }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wizyta/1
  # PATCH/PUT /wizyta/1.json
  def update
    respond_to do |format|
      if @wizytum.update(wizytum_params)
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully updated.' }
        format.json { render :show, status: :ok, location: @wizytum }
      else
        format.html { render :edit }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizyta/1
  # DELETE /wizyta/1.json
  def destroy
    @wizytum.destroy
    respond_to do |format|
      format.html { redirect_to wizyta_url, notice: 'Wizytum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wizytum
      @wizytum = Wizytum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wizytum_params
      params.require(:wizytum).permit(:ID_wizyty, :ID_lekarza, :ID_pacjenta, :ID_recepcjonisty, :termin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archiwums_helper.rb
module ArchiwumsHelper
end

app/helpers/oddzialies_helper.rb
module OddzialiesHelper
end

app/helpers/pacjents_helper.rb
module PacjentsHelper
end

app/helpers/prac2oddzials_helper.rb
module Prac2oddzialsHelper
end

app/helpers/pracowniks_helper.rb
module PracowniksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(pracownik)
	session[:pracownik_id] = pracownik.id
end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/terminarzs_helper.rb
module TerminarzsHelper
end

app/helpers/wizyta_helper.rb
module WizytaHelper
end

app/views/pracowniks/_form.html.erb
<%= form_for(@pracownik) do |f| %>
  <% if @pracownik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pracownik.errors.count, "error") %> prohibited this pracownik from being saved:</h2>

      <ul>
      <% @pracownik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ID_pracownika %><br>
    <%= f.number_field :ID_pracownika %>
  </div>
  <div class="field">
    <%= f.label :ID_rodzajprac %><br>
    <%= f.number_field :ID_rodzajprac %>
  </div>
  <div class="field">
    <%= f.label :imie %><br>
    <%= f.text_field :imie %>
  </div>
  <div class="field">
    <%= f.label :nazwisko %><br>
    <%= f.text_field :nazwisko %>
  </div>
  <div class="field">
    <%= f.label :pesel %><br>
    <%= f.number_field :pesel %>
  </div>
  <div class="field">
    <%= f.label :data_zatrudnienia %><br>
    <%= f.date_select :data_zatrudnienia %>
  </div>
  <div class="field">
    <%= f.label :zarobki %><br>
    <%= f.text_field :zarobki %>
  </div>
  <div class="field">
    <%= f.label :aktywny %><br>
    <%= f.check_box :aktywny %>
  </div>
<br><br>
<div class="field">
<%= f.label :password %><br>
<%= f.password_field :password, id: :pracownik_password %>
</div>

<div class="field">
<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation, id: :pracownik_password_confirmation %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pracowniks/edit.html.erb
<h1>Editing Pracownik</h1>

<%= render 'form' %>

<%= link_to 'Show', @pracownik %> |
<%= link_to 'Back', pracowniks_path %>

app/views/pracowniks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pracowniks</h1>

<table>
  <thead>
    <tr>
      <th>Id pracownika</th>
      <th>Id rodzajprac</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Pesel</th>
      <th>Data zatrudnienia</th>
      <th>Zarobki</th>
      <th>Aktywny</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pracowniks.each do |pracownik| %>
      <tr>
        <td><%= pracownik.ID_pracownika %></td>
        <td><%= pracownik.ID_rodzajprac %></td>
        <td><%= pracownik.imie %></td>
        <td><%= pracownik.nazwisko %></td>
        <td><%= pracownik.pesel %></td>
        <td><%= pracownik.data_zatrudnienia %></td>
        <td><%= pracownik.zarobki %></td>
        <td><%= pracownik.aktywny %></td>
        <td><%= link_to 'Show', pracownik %></td>
        <td><%= link_to 'Edit', edit_pracownik_path(pracownik) %></td>
        <td><%= link_to 'Destroy', pracownik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pracownik', new_pracownik_path %>

app/views/pracowniks/new.html.erb
<h1>New Pracownik</h1>

<%= render 'form' %>

<%= link_to 'Back', pracowniks_path %>

app/views/pracowniks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id pracownika:</strong>
  <%= @pracownik.ID_pracownika %>
</p>

<p>
  <strong>Id rodzajprac:</strong>
  <%= @pracownik.ID_rodzajprac %>
</p>

<p>
  <strong>Imie:</strong>
  <%= @pracownik.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @pracownik.nazwisko %>
</p>

<p>
  <strong>Pesel:</strong>
  <%= @pracownik.pesel %>
</p>

<p>
  <strong>Data zatrudnienia:</strong>
  <%= @pracownik.data_zatrudnienia %>
</p>

<p>
  <strong>Zarobki:</strong>
  <%= @pracownik.zarobki %>
</p>

<p>
  <strong>Aktywny:</strong>
  <%= @pracownik.aktywny %>
</p>

<%= link_to 'Edit', edit_pracownik_path(@pracownik) %> |
<%= link_to 'Back', pracowniks_path %>