config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

root to: 'static#index'

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout',
to: 'sessions#destroy'

  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :pracowniks
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzials
  resources :pracowniks
  resources :hehies
  resources :hehs
  resources :hehehs
  resources :hehs
  resources :hehehs
  resources :hehehs
  resources :hehes
  resources :specjalizacjas
  resources :prac2specjalizacjas
  resources :oddzialies
  resources :prac2oddzials
  resources :pracowniks
  resources :rodzaj_pracownikas
  resources :wozyta
  resources :archiwums
  resources :pacjents
  resources :terminarzs
  resources :students
  resources :pracowniks
  resources :pracownikis
  resources :pracowniks

end

app/models/archiwum.rb
class Archiwum < ActiveRecord::Base
end

app/models/oddzialy.rb
class Oddzialy < ActiveRecord::Base
has_many :prac2oddzials
end

app/models/pacjent.rb
class Pacjent < ActiveRecord::Base
has_many :wizytums
end

app/models/prac2oddzial.rb
class Prac2oddzial < ActiveRecord::Base
end

app/models/prac2specjalizacja.rb
class Prac2specjalizacja < ActiveRecord::Base
end

app/models/pracownik.rb
class Pracownik < ActiveRecord::Base
has_many :prac2oddzials
has_many :prac2specjalizacjas
has_many :wizytums
has_many :terminarzs

has_secure_password
validates :imie, presence: true
validates :nazwisko, presence: true
validates :pesel, presence: true, uniqueness: true, length: { in: 3..50 }


end

app/models/rodzaj_pracownika.rb
class RodzajPracownika < ActiveRecord::Base
has_many :Pracowniks
end

app/models/specjalizacja.rb
class Specjalizacja < ActiveRecord::Base
has_many :prac2specjalizacjas
end

app/models/terminarz.rb
class Terminarz < ActiveRecord::Base
end

app/models/wizytum.rb
class Wizytum < ActiveRecord::Base
has_many :archiwums
end

app/controllers/oddzialies_controller.rb
class OddzialiesController < ApplicationController
  before_action :set_oddzialy, only: [:show, :edit, :update, :destroy]

  # GET /oddzialies
  # GET /oddzialies.json
  def index
    @oddzialies = Oddzialy.all
  end

  # GET /oddzialies/1
  # GET /oddzialies/1.json
  def show
  end

  # GET /oddzialies/new
  def new
    @oddzialy = Oddzialy.new
  end

  # GET /oddzialies/1/edit
  def edit
  end

  # POST /oddzialies
  # POST /oddzialies.json
  def create
    @oddzialy = Oddzialy.new(oddzialy_params)

    respond_to do |format|
      if @oddzialy.save
        format.html { redirect_to @oddzialy, notice: 'Oddzialy was successfully created.' }
        format.json { render :show, status: :created, location: @oddzialy }
      else
        format.html { render :new }
        format.json { render json: @oddzialy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oddzialies/1
  # PATCH/PUT /oddzialies/1.json
  def update
    respond_to do |format|
      if @oddzialy.update(oddzialy_params)
        format.html { redirect_to @oddzialy, notice: 'Oddzialy was successfully updated.' }
        format.json { render :show, status: :ok, location: @oddzialy }
      else
        format.html { render :edit }
        format.json { render json: @oddzialy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oddzialies/1
  # DELETE /oddzialies/1.json
  def destroy
    @oddzialy.destroy
    respond_to do |format|
      format.html { redirect_to oddzialies_url, notice: 'Oddzialy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oddzialy
      @oddzialy = Oddzialy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oddzialy_params
      params.require(:oddzialy).permit(:ID_oddzialu, :oddzial)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

def index
@some_variable = 123
@pracowniks=Pracownik.all

end
end

app/controllers/wizyta_controller.rb
class WizytaController < ApplicationController
  before_action :set_wizytum, only: [:show, :edit, :update, :destroy]

  # GET /wizyta
  # GET /wizyta.json
  def index
    @wizyta = Wizytum.all
  end

  # GET /wizyta/1
  # GET /wizyta/1.json
  def show
  end

  # GET /wizyta/new
  def new
    @wizytum = Wizytum.new
  end

  # GET /wizyta/1/edit
  def edit
  end

  # POST /wizyta
  # POST /wizyta.json
  def create
    @wizytum = Wizytum.new(wizytum_params)

    respond_to do |format|
      if @wizytum.save
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully created.' }
        format.json { render :show, status: :created, location: @wizytum }
      else
        format.html { render :new }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wizyta/1
  # PATCH/PUT /wizyta/1.json
  def update
    respond_to do |format|
      if @wizytum.update(wizytum_params)
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully updated.' }
        format.json { render :show, status: :ok, location: @wizytum }
      else
        format.html { render :edit }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizyta/1
  # DELETE /wizyta/1.json
  def destroy
    @wizytum.destroy
    respond_to do |format|
      format.html { redirect_to wizyta_url, notice: 'Wizytum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wizytum
      @wizytum = Wizytum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wizytum_params
      params.require(:wizytum).permit(:ID_wizyty, :ID_lekarza, :ID_pacjenta, :ID_recepcjonisty, :termin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archiwums_helper.rb
module ArchiwumsHelper
end

app/helpers/oddzialies_helper.rb
module OddzialiesHelper
end

app/helpers/pacjents_helper.rb
module PacjentsHelper
end

app/helpers/prac2oddzials_helper.rb
module Prac2oddzialsHelper
end

app/helpers/pracowniks_helper.rb
module PracowniksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(pracownik)
	session[:pracownik_id] = pracownik.id
end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/terminarzs_helper.rb
module TerminarzsHelper
end

app/helpers/wizyta_helper.rb
module WizytaHelper
end

app/views/oddzialies/_form.html.erb
<%= form_for(@oddzialy) do |f| %>
  <% if @oddzialy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oddzialy.errors.count, "error") %> prohibited this oddzialy from being saved:</h2>

      <ul>
      <% @oddzialy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ID_oddzialu %><br>
    <%= f.number_field :ID_oddzialu %>
  </div>
  <div class="field">
    <%= f.label :oddzial %><br>
    <%= f.text_field :oddzial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oddzialies/edit.html.erb
<h1>Editing Oddzialy</h1>

<%= render 'form' %>

<%= link_to 'Show', @oddzialy %> |
<%= link_to 'Back', oddzialies_path %>

app/views/oddzialies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Oddzialies</h1>

<table>
  <thead>
    <tr>
      <th>Id oddzialu</th>
      <th>Oddzial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oddzialies.each do |oddzialy| %>
      <tr>
        <td><%= oddzialy.ID_oddzialu %></td>
        <td><%= oddzialy.oddzial %></td>
        <td><%= link_to 'Show', oddzialy %></td>
        <td><%= link_to 'Edit', edit_oddzialy_path(oddzialy) %></td>
        <td><%= link_to 'Destroy', oddzialy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oddzialy', new_oddzialy_path %>

app/views/oddzialies/new.html.erb
<h1>New Oddzialy</h1>

<%= render 'form' %>

<%= link_to 'Back', oddzialies_path %>

app/views/oddzialies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id oddzialu:</strong>
  <%= @oddzialy.ID_oddzialu %>
</p>

<p>
  <strong>Oddzial:</strong>
  <%= @oddzialy.oddzial %>
</p>

<%= link_to 'Edit', edit_oddzialy_path(@oddzialy) %> |
<%= link_to 'Back', oddzialies_path %>