config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

root to: 'static#index'

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout',
to: 'sessions#destroy'

  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :pracowniks
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :archiwums
  resources :pacjents
  resources :wizyta
  resources :terminarzs
  resources :prac2specjalizacjas
  resources :specjalizacjas
  resources :prac2oddzials
  resources :oddzialies
  resources :rodzaj_pracownikas
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzialies
  resources :pracowniks
  resources :oddzials
  resources :pracowniks
  resources :hehies
  resources :hehs
  resources :hehehs
  resources :hehs
  resources :hehehs
  resources :hehehs
  resources :hehes
  resources :specjalizacjas
  resources :prac2specjalizacjas
  resources :oddzialies
  resources :prac2oddzials
  resources :pracowniks
  resources :rodzaj_pracownikas
  resources :wozyta
  resources :archiwums
  resources :pacjents
  resources :terminarzs
  resources :students
  resources :pracowniks
  resources :pracownikis
  resources :pracowniks

end

app/models/archiwum.rb
class Archiwum < ActiveRecord::Base
end

app/models/oddzialy.rb
class Oddzialy < ActiveRecord::Base
has_many :prac2oddzials
end

app/models/pacjent.rb
class Pacjent < ActiveRecord::Base
has_many :wizytums
end

app/models/prac2oddzial.rb
class Prac2oddzial < ActiveRecord::Base
end

app/models/prac2specjalizacja.rb
class Prac2specjalizacja < ActiveRecord::Base
end

app/models/pracownik.rb
class Pracownik < ActiveRecord::Base
has_many :prac2oddzials
has_many :prac2specjalizacjas
has_many :wizytums
has_many :terminarzs

has_secure_password
validates :imie, presence: true
validates :nazwisko, presence: true
validates :pesel, presence: true, uniqueness: true, length: { in: 3..50 }


end

app/models/rodzaj_pracownika.rb
class RodzajPracownika < ActiveRecord::Base
has_many :Pracowniks
end

app/models/specjalizacja.rb
class Specjalizacja < ActiveRecord::Base
has_many :prac2specjalizacjas
end

app/models/terminarz.rb
class Terminarz < ActiveRecord::Base
end

app/models/wizytum.rb
class Wizytum < ActiveRecord::Base
has_many :archiwums
end

app/controllers/archiwums_controller.rb
class ArchiwumsController < ApplicationController
  before_action :set_archiwum, only: [:show, :edit, :update, :destroy]

  # GET /archiwums
  # GET /archiwums.json
  def index
    @archiwums = Archiwum.all
  end

  # GET /archiwums/1
  # GET /archiwums/1.json
  def show
  end

  # GET /archiwums/new
  def new
    @archiwum = Archiwum.new
  end

  # GET /archiwums/1/edit
  def edit
  end

  # POST /archiwums
  # POST /archiwums.json
  def create
    @archiwum = Archiwum.new(archiwum_params)

    respond_to do |format|
      if @archiwum.save
        format.html { redirect_to @archiwum, notice: 'Archiwum was successfully created.' }
        format.json { render :show, status: :created, location: @archiwum }
      else
        format.html { render :new }
        format.json { render json: @archiwum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archiwums/1
  # PATCH/PUT /archiwums/1.json
  def update
    respond_to do |format|
      if @archiwum.update(archiwum_params)
        format.html { redirect_to @archiwum, notice: 'Archiwum was successfully updated.' }
        format.json { render :show, status: :ok, location: @archiwum }
      else
        format.html { render :edit }
        format.json { render json: @archiwum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archiwums/1
  # DELETE /archiwums/1.json
  def destroy
    @archiwum.destroy
    respond_to do |format|
      format.html { redirect_to archiwums_url, notice: 'Archiwum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archiwum
      @archiwum = Archiwum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archiwum_params
      params.require(:archiwum).permit(:ID_wpisu, :ID_wizyty, :historia, :inf_dod)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

def index
@some_variable = 123
@pracowniks=Pracownik.all

end
end

app/controllers/wizyta_controller.rb
class WizytaController < ApplicationController
  before_action :set_wizytum, only: [:show, :edit, :update, :destroy]

  # GET /wizyta
  # GET /wizyta.json
  def index
    @wizyta = Wizytum.all
  end

  # GET /wizyta/1
  # GET /wizyta/1.json
  def show
  end

  # GET /wizyta/new
  def new
    @wizytum = Wizytum.new
  end

  # GET /wizyta/1/edit
  def edit
  end

  # POST /wizyta
  # POST /wizyta.json
  def create
    @wizytum = Wizytum.new(wizytum_params)

    respond_to do |format|
      if @wizytum.save
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully created.' }
        format.json { render :show, status: :created, location: @wizytum }
      else
        format.html { render :new }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wizyta/1
  # PATCH/PUT /wizyta/1.json
  def update
    respond_to do |format|
      if @wizytum.update(wizytum_params)
        format.html { redirect_to @wizytum, notice: 'Wizytum was successfully updated.' }
        format.json { render :show, status: :ok, location: @wizytum }
      else
        format.html { render :edit }
        format.json { render json: @wizytum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizyta/1
  # DELETE /wizyta/1.json
  def destroy
    @wizytum.destroy
    respond_to do |format|
      format.html { redirect_to wizyta_url, notice: 'Wizytum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wizytum
      @wizytum = Wizytum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wizytum_params
      params.require(:wizytum).permit(:ID_wizyty, :ID_lekarza, :ID_pacjenta, :ID_recepcjonisty, :termin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archiwums_helper.rb
module ArchiwumsHelper
end

app/helpers/oddzialies_helper.rb
module OddzialiesHelper
end

app/helpers/pacjents_helper.rb
module PacjentsHelper
end

app/helpers/prac2oddzials_helper.rb
module Prac2oddzialsHelper
end

app/helpers/pracowniks_helper.rb
module PracowniksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(pracownik)
	session[:pracownik_id] = pracownik.id
end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/terminarzs_helper.rb
module TerminarzsHelper
end

app/helpers/wizyta_helper.rb
module WizytaHelper
end

app/views/archiwums/_form.html.erb
<%= form_for(@archiwum) do |f| %>
  <% if @archiwum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archiwum.errors.count, "error") %> prohibited this archiwum from being saved:</h2>

      <ul>
      <% @archiwum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ID_wpisu %><br>
    <%= f.number_field :ID_wpisu %>
  </div>
  <div class="field">
    <%= f.label :ID_wizyty %><br>
    <%= f.number_field :ID_wizyty %>
  </div>
  <div class="field">
    <%= f.label :historia %><br>
    <%= f.text_field :historia %>
  </div>
  <div class="field">
    <%= f.label :inf_dod %><br>
    <%= f.text_field :inf_dod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archiwums/edit.html.erb
<h1>Editing Archiwum</h1>

<%= render 'form' %>

<%= link_to 'Show', @archiwum %> |
<%= link_to 'Back', archiwums_path %>

app/views/archiwums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Archiwums</h1>

<table>
  <thead>
    <tr>
      <th>Id wpisu</th>
      <th>Id wizyty</th>
      <th>Historia</th>
      <th>Inf dod</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archiwums.each do |archiwum| %>
      <tr>
        <td><%= archiwum.ID_wpisu %></td>
        <td><%= archiwum.ID_wizyty %></td>
        <td><%= archiwum.historia %></td>
        <td><%= archiwum.inf_dod %></td>
        <td><%= link_to 'Show', archiwum %></td>
        <td><%= link_to 'Edit', edit_archiwum_path(archiwum) %></td>
        <td><%= link_to 'Destroy', archiwum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archiwum', new_archiwum_path %>

app/views/archiwums/new.html.erb
<h1>New Archiwum</h1>

<%= render 'form' %>

<%= link_to 'Back', archiwums_path %>

app/views/archiwums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id wpisu:</strong>
  <%= @archiwum.ID_wpisu %>
</p>

<p>
  <strong>Id wizyty:</strong>
  <%= @archiwum.ID_wizyty %>
</p>

<p>
  <strong>Historia:</strong>
  <%= @archiwum.historia %>
</p>

<p>
  <strong>Inf dod:</strong>
  <%= @archiwum.inf_dod %>
</p>

<%= link_to 'Edit', edit_archiwum_path(@archiwum) %> |
<%= link_to 'Back', archiwums_path %>